import type { NextPage } from 'next'
import { useRef, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/about'
import Employment from '../components/employment'
import Languages from '../components/languages'
import Masthead from '../components/masthead'
import Projects from '../components/projects'
import Skills from '../components/skills'
import { useEffect } from 'react'
import { useContext } from 'react'
import { ScrollContext } from '../utils/scroll-observer'

const Home: NextPage = () => {
  // const scrollContext = useContext(ScrollContext);
  return (
    <div className='font-jakarta'>
      <Head>
        <title>Miraquel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <About className="px-11 md:px-12 lg:px-14 xl:px-32 flex flex-col bg-white py-11 md:py-12 lg:py-14 xl:py-20" />
      <Languages className="min-h-screen flex flex-col place-content-center bg-white" />
      <Skills className="min-h-screen bg-gradient-to-b from-[#D9AFD9] to-[#97D9E1] py-11" />
      <Employment className='flex flex-col min-h-screen bg-gradient-to-b from-[#FFFB7D] to-[#85FFBD]' />
      <Projects />
    </div>
  )
}

export default Home
