import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/about'
import Masthead from '../components/masthead'

const Home: NextPage = () => {
  return (
    <div className='font-jakarta'>
      <Head>
        <title>Miraquel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Masthead />
      <About />
    </div>
  )
}

export default Home
